consumer:
  bootstrap-servers: localhost:9092
  topics:
  - outbox.event.hbi.hosts
  - host-inventory.hbi.hosts
  retry-options:
    consumer-max-retries: 3
    operation-max-retries: 4
    backoff-factor: 5
  auth:
    enabled: false
client:
  enabled: true
  url: "localhost:8081"
  enable-oidc-auth: false
  insecure: true
log:
  level: "info"
