apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: kessel-inventory-consumer
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      name: kessel-inventory-consumer
    spec:
      envName: ${ENV_NAME}
      kafkaTopics:
      - topicName: outbox.event.hbi.hosts
      - topicName: host-inventory.hbi.hosts
      optionalDependencies:
        - kessel-inventory
        - kessel-relations
      deployments:
        - name: service
          replicas: ${{REPLICAS}}
          podSpec:
            image: ${KIC_IMAGE}:${IMAGE_TAG}
            imagePullPolicy: Always
            command: ["inventory-consumer"]
            args: ["start"]
            env:
            - name: CLOWDER_ENABLED
              value: "true"
            - name: INVENTORY_CONSUMER_CONFIG
              value: "/inventory/kic-config.yaml"
            volumeMounts:
                - name: config-volume
                  mountPath: "/inventory"
                - name: kafka-ca-certs
                  mountPath: "/kafka-ca-certs"
                - name: ca-certs
                  mountPath: "/ca-certs"
            volumes:
              - name: config-volume
                secret:
                  secretName: kessel-inventory-consumer-config
              - name: kafka-ca-certs
                secret:
                  secretName: ${CA_CERT_SECRET}
                  optional: true
              - name: ca-certs
                configMap:
                  name: openshift-service-ca.crt
            readinessProbe:
              exec:
                command: ["inventory-consumer", "readyz"]
              initialDelaySeconds: 15
              periodSeconds: 30
              timeoutSeconds: 5
              failureThreshold: 3
            resources:
              requests:
                memory: ${KIC_REQUESTS_MEMORY}
                cpu: ${KIC_REQUESTS_CPU}
              limits:
                memory: ${KIC_LIMITS_MEMORY}
                cpu: ${KIC_LIMITS_CPU}
          webServices:
            public:
              enabled: false

  - kind: PodDisruptionBudget
    apiVersion: policy/v1
    metadata:
      name: kessel-inventory-consumer-pdb
    spec:
      minAvailable: 1
      selector:
        matchLabels:
          app: kessel-inventory-consumer

parameters:
  - description: ClowdEnvironment name (ephemeral, stage, prod)
    name: ENV_NAME
    required: true
  - description: App Image
    name: KIC_IMAGE
    value: quay.io/redhat-services-prod/project-kessel-tenant/kessel-inventory-consumer/inventory-consumer
  - description: Image Tag
    name: IMAGE_TAG
    required: true
    value: latest
  - description: Number of replicas
    name: REPLICAS
    value: "3"
  - description: Name of Secret that contains the Kafka clusters' CA Cert (if required)
    name: CA_CERT_SECRET
    value: kessel-kafka-connect-config
  - name: KIC_REQUESTS_MEMORY
    description: Memory request for Inventory Consumer service
    value: '512Mi'
  - name: KIC_REQUESTS_CPU
    description: CPU request for Inventory Consumer service
    value: '150m'
  - name: KIC_LIMITS_MEMORY
    description: Memory limit for Inventory Consumer service
    value: '1Gi'
  - name: KIC_LIMITS_CPU
    description: CPU limit for Inventory Consumer service
    value: '300m'
