apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: kessel-inventory-consumer
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: kic-config
    data:
      kic-config.yaml: |
        consumer:
          topics:
          - outbox.event.hbi.hosts
          - host-inventory.hbi.hosts
          retry-options:
            consumer-max-retries: 3
            operation-max-retries: 4
            backoff-factor: 5
          auth:
            enabled: false
        client:
          enabled: true
          url: "kessel-inventory-api:9000"
          enable-oidc-auth: false
          insecure: true
        log:
          level: "info"

  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      name: kessel-inventory-consumer
    spec:
      envName: ${ENV_NAME}
      kafkaTopics:
      - topicName: outbox.event.hbi.hosts
        partitions: ${{PARTITIONS}}
        replicas: 3
      - topicName: host-inventory.hbi.hosts
        partitions: ${{PARTITIONS}}
        replicas: 3
      optionalDependencies:
        - kessel-inventory
        - kessel-relations
      deployments:
        - name: service
          replicas: ${{REPLICAS}}
          podSpec:
            image: ${KIC_IMAGE}:${IMAGE_TAG}
            imagePullPolicy: Always
            command: ["inventory-consumer"]
            args: ["start"]
            env:
            - name: CLOWDER_ENABLED
              value: "true"
            - name: INVENTORY_CONSUMER_CONFIG
              value: "/inventory/kic-config.yaml"
            volumeMounts:
                - name: config-volume
                  mountPath: "/inventory"
            volumes:
              - name: config-volume
                configMap:
                  name: kic-config
            readinessProbe:
              exec:
                command: ["inventory-consumer", "readyz"]
              initialDelaySeconds: 15
              periodSeconds: 30
              timeoutSeconds: 5
              failureThreshold: 3
            resources:
              requests:
                memory: ${KIC_REQUESTS_MEMORY}
                cpu: ${KIC_REQUESTS_CPU}
              limits:
                memory: ${KIC_LIMITS_MEMORY}
                cpu: ${KIC_LIMITS_CPU}
          webServices:
            public:
              enabled: false

parameters:
  - description: ClowdEnvironment name (ephemeral, stage, prod)
    name: ENV_NAME
    required: true
  - description: App Image
    name: KIC_IMAGE
    value: quay.io/redhat-services-prod/project-kessel-tenant/kessel-inventory-consumer/inventory-consumer
  - description: Image Tag
    name: IMAGE_TAG
    required: true
    value: latest
  - description: Number of replicas
    name: REPLICAS
    value: "1"
  - name: PARTITIONS
    description: Number of partitions to configure for a topic
    value: "1"
  - name: KIC_REQUESTS_MEMORY
    description: Memory request for Inventory Consumer service
    value: '512Mi'
  - name: KIC_REQUESTS_CPU
    description: CPU request for Inventory Consumer service
    value: '150m'
  - name: KIC_LIMITS_MEMORY
    description: Memory limit for Inventory Consumer service
    value: '1Gi'
  - name: KIC_LIMITS_CPU
    description: CPU limit for Inventory Consumer service
    value: '300m'
