{
 "title": "Kessel Inventory Consumer",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "kafka_datasource", "label": "Kafka Datasource", "query": "prometheus" },
   { "name": "outbox_datasource", "label": "Outbox Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Consumer Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Consumers",
   "type": "stat",
   "description": "Number of active consumers (should match number of replicas, may not indicate they are actively consuming depending on partition count)",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(consumer_stats_state{state=\"up\", job=\"kessel-inventory-consumer-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Msgs in Queue",
   "type": "stat",
   "description": "Number of messages remaining in topic to be processed",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(consumer_stats_replyq{job=\"kessel-inventory-consumer-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Rebalance",
   "type": "stat",
   "description": "How long since last rebalance occurred",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(consumer_stats_rebalance_age{job=\"kessel-inventory-consumer-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Lag (messages)",
   "type": "timeseries",
   "description": "Messages are committed in batches of ~10. Lag up to 10 messages can be expected",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aws_kafka_sum_offset_lag_sum{consumer_group='kic'}) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rebalance Events",
   "type": "timeseries",
   "description": "Captures how many rebalance events have occurred over set interval",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "changes(consumer_stats_rebalance_cnt_total{job=\"kessel-inventory-consumer-service\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(consumer_msgs_processed_total{job=\"kessel-inventory-consumer-service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Processing Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(consumer_msg_process_failures_total{job=\"kessel-inventory-consumer-service\"}[$__rate_interval])) / sum(rate(consumer_msgs_processed_total{job=\"kessel-inventory-consumer-service\"}[$__rate_interval])) or sum(up{job=\"kessel-inventory-consumer-service\"}) * 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Error Rate",
   "type": "timeseries",
   "description": "Errors related to the Consumer and not message processing",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(consumer_errors_total{job=\"kessel-inventory-consumer-service\"}[$__rate_interval])) / sum(rate(consumer_msgs_processed_total{job=\"kessel-inventory-consumer-service\"}[$__rate_interval])) or sum(up{job=\"kessel-inventory-consumer-service\"}) * 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Error Events",
   "type": "table",
   "description": "Recent Kafka Error Event Messages Processed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "consumer_kafka_error_events_total{job=\"kessel-inventory-consumer-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication (by Service Provider)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }
  },
  {
   "title": "HBI Outbox Events (last 15 mins)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(inventory_outbox_save_successes_total[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HBI Processed Events (last 15 mins)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(consumer_msgs_processed_total{job=\"kessel-inventory-consumer-service\",topic=\"outbox.event.hbi.hosts\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "E2E Lag (Messages over last 15 mins)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(inventory_outbox_save_successes_total[15m]))",
     "legendFormat": "outbox"
    },
    {
     "expr": "sum(increase(consumer_msgs_processed_total{job='kessel-inventory-consumer-service', topic='outbox.event.hbi.hosts'}[15m]))",
     "legendFormat": "processed"
    }
   ]
  },
  {
   "title": "E2E Replication Lag Rate",
   "type": "timeseries",
   "description": "Lag from point where resource is written to outbox table, to consumed and processed by Kessel Inventory Consumer (over range)",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(inventory_outbox_save_successes_total[$__range]))",
     "legendFormat": "outbox"
    },
    {
     "expr": "sum(rate(consumer_msgs_processed_total{job=\"kessel-inventory-consumer-service\",topic=\"outbox.event.hbi.hosts\"}[$__range]))",
     "legendFormat": "processed"
    }
   ]
  },
  {
   "title": "Consumer Error Rate (HBI Outbox)",
   "type": "timeseries",
   "description": "over range",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(consumer_msg_process_failures_total{job=\"kessel-inventory-consumer-service\", topic=\"outbox.event.hbi.hosts\"}[$__rate_interval])) / sum(rate(consumer_msgs_processed_total{job=\"kessel-inventory-consumer-service\", topic=\"outbox.event.hbi.hosts\"}[$__rate_interval])) or sum(up{job=\"kessel-inventory-consumer-service\"}) * 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}